/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Design;

import com.mysql.cj.jdbc.Driver;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Transaksi extends javax.swing.JDialog {

    public Transaksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

    }

    boolean modeSimpan = true;
    boolean dupe;

    private boolean regDriver() {
        try {
            DriverManager.registerDriver(new Driver());
            return true;
        } catch (SQLException e) {
            System.out.println(e);
            return false;
        }
    }

    private Connection setConnection() throws SQLException {
        regDriver();
        String url = "jdbc:mysql://localhost:3306/spp_1.1";
        String user = "root";
        String passwd = "";
        return DriverManager.getConnection(url, user, passwd);
    }

    private void Read() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            Statement stm = setConnection().createStatement();
            ResultSet rs = stm.executeQuery("select transaksi.id_transaksi,transaksi.id_admin,transaksi.tanggal,siswa.nama_siswa,transaksi.nisn,transaksi.id_kelas,transaksi.semester from transaksi inner join siswa on transaksi.nisn = siswa.nisn");
            ResultSetMetaData rsmt = rs.getMetaData();
            model.setRowCount(0);
            model.fireTableDataChanged();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(rsmt.getColumnName(1)), rs.getString(rsmt.getColumnName(2)),
                    rs.getString(rsmt.getColumnName(3)), rs.getString(rsmt.getColumnName(4)),
                    rs.getString(rsmt.getColumnName(5)), rs.getString(rsmt.getColumnName(6)), rs.getString(rsmt.getColumnName(7))});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean Search(String kode) {
        try {
            Statement stm = setConnection().createStatement();
            ResultSet rs = stm.executeQuery("select id_transaksi from transaksi where id_transaksi =" + kode);
            if (rs.next()) {
                return true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.println("fuck");
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_admin = new javax.swing.JTextField();
        nisn = new javax.swing.JTextField();
        id_transaksi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id_kelas = new javax.swing.JTextField();
        semester = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tanggal = new com.github.lgooddatepicker.components.DatePicker();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        baru = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Kelas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setText("DATA TRANSAKSI");
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));

        jLabel2.setText("ID TRANSAKSI");

        jLabel5.setText("NISN");

        jLabel4.setText("TANGGAL");

        jLabel3.setText("ID ADMIN");

        id_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_adminKeyTyped(evt);
            }
        });

        nisn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nisnKeyTyped(evt);
            }
        });

        id_transaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_transaksiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_transaksiKeyTyped(evt);
            }
        });

        jLabel8.setText("INPUTKAN DATA TRANSAKSI");
        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel7.setText("Enter untuk melanjutkan");
        jLabel7.setEnabled(false);

        jLabel6.setText("ID KELAS");

        id_kelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_kelasKeyTyped(evt);
            }
        });

        semester.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                semesterKeyTyped(evt);
            }
        });

        jLabel9.setText("SEMESTER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(id_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(id_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(id_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nisn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nisn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(id_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID TRANSAKSI", "ID ADMIN", "TANGGAL", "Nama Siswa", "NISN", "ID KELAS", "SEMESTER"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        baru.setText("Baru");
        baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(baru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapus)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus)
                    .addComponent(batal)
                    .addComponent(ubah)
                    .addComponent(simpan)
                    .addComponent(baru))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Read();
        id_transaksi.setEnabled(false);
        id_admin.setEnabled(false);
        tanggal.setEnabled(false);
        nisn.setEnabled(false);
        id_kelas.setEnabled(false);
        semester.setEnabled(false);
        baru.setEnabled(true);
        simpan.setEnabled(false);
        ubah.setEnabled(false);
        batal.setEnabled(false);
        hapus.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruActionPerformed
        modeSimpan = true;
        id_transaksi.setEnabled(true);
        id_admin.setEnabled(false);
        tanggal.setEnabled(false);
        nisn.setEnabled(false);
        id_kelas.setEnabled(false);
        semester.setEnabled(false);
        baru.setEnabled(false);
        simpan.setEnabled(true);
        ubah.setEnabled(false);
        batal.setEnabled(true);
        hapus.setEnabled(false);
    }//GEN-LAST:event_baruActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (id_transaksi.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "id tidak boleh kosong!", // isi pesan
                    "Informasi", // judul pesan
                    JOptionPane.INFORMATION_MESSAGE
            );
            id_transaksi.requestFocus();
        } else if (id_admin.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "id tidak boleh kosong!", // isi pesan
                    "Informasi", // judul pesan
                    JOptionPane.INFORMATION_MESSAGE
            );
            id_admin.requestFocus();
        } else if (tanggal.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "tanggal tidak boleh kosong!", // isi pesan
                    "Informasi", // judul pesan
                    JOptionPane.INFORMATION_MESSAGE
            );
            tanggal.requestFocus();
        } else if (nisn.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "nisn tidak boleh kosong!", // isi pesan
                    "Informasi", // judul pesan
                    JOptionPane.INFORMATION_MESSAGE
            );
            nisn.requestFocus();
        } else if (id_kelas.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "kelas tidak boleh kosong!", // isi pesan
                    "Informasi", // judul pesan
                    JOptionPane.INFORMATION_MESSAGE
            );
            id_kelas.requestFocus();
        } else if (semester.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "semester tidak boleh kosong!", // isi pesan
                    "Informasi", // judul pesan
                    JOptionPane.INFORMATION_MESSAGE
            );
            semester.requestFocus();
        } else {
            if (modeSimpan == true) { // save
                try {
                    PreparedStatement prpr = setConnection().prepareStatement("insert into transaksi values(?,?,?,?,?,?)");
                    prpr.setString(1, id_transaksi.getText());
                    prpr.setString(2, id_admin.getText());
                    prpr.setString(3, tanggal.toString());
                    prpr.setString(4, nisn.getText());
                    prpr.setString(5, id_kelas.getText());
                    prpr.setString(6, semester.getText());
                    var i = prpr.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(siswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else { // update
                try {
                    PreparedStatement prpr = setConnection().prepareStatement("update transaksi set tanggal = ? where id_transaksi = ?");
                    prpr.setString(1, tanggal.toString());
                    prpr.setString(2, id_transaksi.getText());
                    var i = prpr.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(siswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            batalActionPerformed(evt);
            Read();
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        id_transaksi.setEnabled(false);
        id_transaksi.setText("");
        id_admin.setEnabled(false);
        id_admin.setText("");
        tanggal.setEnabled(false);
        tanggal.setText("");
        nisn.setEnabled(false);
        nisn.setText("");
        id_kelas.setEnabled(false);
        id_kelas.setText("");
        semester.setEnabled(false);
        semester.setText("");
        baru.setEnabled(true);
        simpan.setEnabled(false);
        ubah.setEnabled(false);
        batal.setEnabled(false);
        hapus.setEnabled(false);
    }//GEN-LAST:event_batalActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih salah satu baris yang akan dihapus!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            int pilihan = JOptionPane.showConfirmDialog(
                    this,
                    "Apakah yakin akan menghapus data?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION
            );
            if (pilihan == 0) { // tombol yes dipilih
                try {
                    PreparedStatement prpr = setConnection().prepareStatement("delete from transaksi where id_transaksi = ?");
                    prpr.setString(1, id_transaksi.getText());
                    var i = prpr.executeUpdate();
                    Read();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Data Jurusan Digunakan di Tabel lain");
                }
                batalActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        modeSimpan = false;
        id_transaksi.setEnabled(false);
        id_admin.setEnabled(false);
        tanggal.setEnabled(true);
        nisn.setEnabled(false);
        id_kelas.setEnabled(false);
        semester.setEnabled(false);
        baru.setEnabled(false);
        simpan.setEnabled(true);
        ubah.setEnabled(false);
        batal.setEnabled(true);
        hapus.setEnabled(false);
    }//GEN-LAST:event_ubahActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih salah satu baris yang diinginkan!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            id_transaksi.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            id_admin.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            tanggal.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            nisn.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            id_kelas.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            semester.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            baru.setEnabled(false);
            simpan.setEnabled(false);
            ubah.setEnabled(true);
            batal.setEnabled(true);
            hapus.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void id_transaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_transaksiKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dupe = Search(id_transaksi.getText());
            if (dupe == true) {
                dupe = false;
                int pilihan;
                pilihan = JOptionPane.showConfirmDialog(
                        this,
                        "data kosong atau id transaksi " + id_transaksi.getText() + " sudah ada!"
                        + "Apakah anda ingin mengubah/menghapus data?",
                        "Konfirmasi",
                        JOptionPane.YES_NO_OPTION);
                if (pilihan == 0) {
                    try {
                        Statement stm = setConnection().createStatement();
//                        ResultSet rs = stm.executeQuery("select id_kelas,nama_siswa,alamat,no_hp,id_angkatan from siswa where nisn =" + nisn.getText());
                        ResultSet rs = stm.executeQuery("select * from transaksi where id_transaksi =" + id_transaksi.getText());
                        ResultSetMetaData rsmt = rs.getMetaData();
                        while (rs.next()) {
                            id_admin.setText(rs.getString(rsmt.getColumnName(1)));
                            tanggal.setText(rs.getString(rsmt.getColumnName(2)));
                            nisn.setText(rs.getString(rsmt.getColumnName(4)));
                            id_kelas.setText(rs.getString(rsmt.getColumnName(5)));
                            semester.setText(rs.getString(rsmt.getColumnName(6)));
                        }
                        id_transaksi.setEnabled(false);
                        id_admin.setEnabled(false);
                        tanggal.setEnabled(true);
                        nisn.setEnabled(false);
                        id_kelas.setEnabled(false);
                        semester.setEnabled(false);
                        baru.setEnabled(false);
                        simpan.setEnabled(true);
                        ubah.setEnabled(false);
                        batal.setEnabled(true);
                        hapus.setEnabled(false);
                        modeSimpan = false;
                    } catch (SQLException e) {
                        System.err.println("Query error");
                    }
                } else {
                    id_transaksi.setText("");
                    id_transaksi.requestFocus();
                }
            } else {
                id_admin.setEnabled(true);
                id_admin.requestFocus();
                tanggal.setEnabled(true);
                nisn.setEnabled(true);
                id_kelas.setEnabled(true);
                semester.setEnabled(true);
                simpan.setEnabled(true);
            }
        }
    }//GEN-LAST:event_id_transaksiKeyReleased

    private void id_transaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_transaksiKeyTyped
        if (id_transaksi.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_id_transaksiKeyTyped

    private void id_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_adminKeyTyped
        if (id_admin.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_id_adminKeyTyped

    private void nisnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nisnKeyTyped
        if (nisn.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_nisnKeyTyped

    private void id_kelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_kelasKeyTyped
        if (id_kelas.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_id_kelasKeyTyped

    private void semesterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semesterKeyTyped
        if (semester.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_semesterKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Transaksi dialog = new Transaksi(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baru;
    private javax.swing.JButton batal;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField id_admin;
    private javax.swing.JTextField id_kelas;
    private javax.swing.JTextField id_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nisn;
    private javax.swing.JTextField semester;
    private javax.swing.JButton simpan;
    private com.github.lgooddatepicker.components.DatePicker tanggal;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
