/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual.Jobsheet_10;

import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import visual.Jobsheet_09.*;

/**
 *
 * @author erdia
 */
public class MainMenu extends javax.swing.JFrame {

    Connection koneksi;

    /**
     * Creates new form Main
     */
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost/polnep";
            String user = "root";
            String passwd = "";
            koneksi = DriverManager.getConnection(url,user,passwd);
        } catch (ClassNotFoundException e) {
            System.out.println("Driver Tidak Titemukan");
        } catch (SQLException e){
            System.out.println("Koneksi Gagal");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jurusan = new javax.swing.JMenuItem();
        prodi = new javax.swing.JMenuItem();
        mhs = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jurusan1 = new javax.swing.JMenuItem();
        prodi1 = new javax.swing.JMenuItem();
        mhs1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Frame");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("APLIKASI GUI KELOLA DATA JURUSAN,PROGRAM STUDI DAN MAHASISWA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenu1.setText("Kelola Data");

        jurusan.setText("Jurusan");
        jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanActionPerformed(evt);
            }
        });
        jMenu1.add(jurusan);

        prodi.setText("Program Studi");
        prodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiActionPerformed(evt);
            }
        });
        jMenu1.add(prodi);

        mhs.setText("Mahasiswa");
        mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhsActionPerformed(evt);
            }
        });
        jMenu1.add(mhs);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kelola Data");

        jurusan1.setText("Jurusan");
        jurusan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusan1ActionPerformed(evt);
            }
        });
        jMenu2.add(jurusan1);

        prodi1.setText("Program Studi");
        prodi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodi1ActionPerformed(evt);
            }
        });
        jMenu2.add(prodi1);

        mhs1.setText("Mahasiswa");
        mhs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhs1ActionPerformed(evt);
            }
        });
        jMenu2.add(mhs1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanActionPerformed
        new KelolaDataJurusan(new javax.swing.JFrame(), true).setVisible(true);
    }//GEN-LAST:event_jurusanActionPerformed

    private void prodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiActionPerformed
        new KelolaDataProdi(new javax.swing.JFrame(), true).setVisible(true);
    }//GEN-LAST:event_prodiActionPerformed

    private void mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhsActionPerformed
        new KelolaDataMahasiswa(new javax.swing.JFrame(), true).setVisible(true);
    }//GEN-LAST:event_mhsActionPerformed

    private void jurusan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusan1ActionPerformed
        try {
            String sourceFileName = "Jurusan.jasper";
            JasperReport jasperReport = (JasperReport) JRLoader.loadObjectFromFile(sourceFileName);
            Map<String, Object> parameters = new HashMap<>();
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, koneksi);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (JRException e) {
            System.err.println("file tidak ditemukan");
        }
    }//GEN-LAST:event_jurusan1ActionPerformed

    private void prodi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodi1ActionPerformed

    private void mhs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mhs1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jurusan;
    private javax.swing.JMenuItem jurusan1;
    private javax.swing.JMenuItem mhs;
    private javax.swing.JMenuItem mhs1;
    private javax.swing.JMenuItem prodi;
    private javax.swing.JMenuItem prodi1;
    // End of variables declaration//GEN-END:variables
}
