/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual.Jobsheet_09;

import com.mysql.cj.jdbc.Driver;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import visual.Jobsheet_08.latihan;

/**
 *
 * @author erdia
 */
public class KelolaDataJurusan extends javax.swing.JDialog {

    /**
     * Creates new form KelolaData
     */
    public KelolaDataJurusan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

    }
    boolean modeSimpan = true;
    boolean dupe;

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name_jurusan = new javax.swing.JTextField();
        kode_jurusan = new javax.swing.JTextField();
        baru = new javax.swing.JButton();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jurusan");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setText("Kode Jurusan");

        jLabel3.setText("Nama Jurusan");

        name_jurusan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name_jurusanKeyTyped(evt);
            }
        });

        kode_jurusan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kode_jurusanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kode_jurusanKeyTyped(evt);
            }
        });

        baru.setText("Baru");
        baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruActionPerformed(evt);
            }
        });

        save.setText("Simpan");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setText("Batal");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        delete.setText("Hapus");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        edit.setText("Ubah");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Jurusan", "Nama Jurusan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.setEditingColumn(0);
        tabel.setEditingRow(0);
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jLabel6.setText("Tekan enter untuk melanjutkan");

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Tekan enter untuk melanjutkan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kode_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(baru)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(save)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(delete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cancel))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(2, 2, 2)
                            .addComponent(name_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addComponent(jLabel6)
                    .addContainerGap(153, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kode_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baru)
                    .addComponent(delete)
                    .addComponent(edit)
                    .addComponent(save)
                    .addComponent(cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(218, 218, 218)
                    .addComponent(jLabel6)
                    .addContainerGap(218, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Kelola Data Jurusan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(460, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean regDriver() {
        try {
            DriverManager.registerDriver(new Driver());
            return true;
        } catch (SQLException e) {
            System.out.println(e);
            return false;
        }
    }

    private Connection setConnection() throws SQLException {
        regDriver();
        String url = "jdbc:mysql://localhost:3306/polnep";
        String user = "root";
        String passwd = "";
        return DriverManager.getConnection(url, user, passwd);
    }

    private void Read() {
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        try {
            Statement stm = setConnection().createStatement();
            ResultSet rs = stm.executeQuery("select * from jurusan");
            ResultSetMetaData rsmt = rs.getMetaData();
            model.setRowCount(0);
            model.fireTableDataChanged();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(rsmt.getColumnName(1)), rs.getString(rsmt.getColumnName(2)),});
            }
        } catch (SQLException ex) {
            Logger.getLogger(latihan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean Search(String kode) {
        try {
            Statement stm = setConnection().createStatement();
            ResultSet rs = stm.executeQuery("select kode_jurusan from jurusan where kode_jurusan =" + kode);
            if (rs.next()) {
                return true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(latihan.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    private void baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruActionPerformed
        // TODO add your handling code here:
        name_jurusan.setEnabled(false);
        kode_jurusan.setEnabled(true);
        kode_jurusan.requestFocus();
        baru.setEnabled(false);
        save.setEnabled(true);
        edit.setEnabled(false);
        delete.setEnabled(false);
        cancel.setEnabled(true);
        modeSimpan = true;
    }//GEN-LAST:event_baruActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        if (kode_jurusan.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "kode jurusan tidak boleh kosong!", // isi pesan
                    "Informasi", // judul pesan
                    JOptionPane.INFORMATION_MESSAGE
            );
            kode_jurusan.requestFocus();
        } else if (name_jurusan.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Nama tidak boleh kosong!", // isi pesan
                    "Informasi", // judul pesan
                    JOptionPane.INFORMATION_MESSAGE
            );
            name_jurusan.requestFocus();
        } else {
            if (modeSimpan == true) { // save
                try {
                    PreparedStatement prpr = setConnection().prepareStatement("insert into jurusan values(?,?)");
                    prpr.setString(1, kode_jurusan.getText());
                    prpr.setString(2, name_jurusan.getText());
                    var i = prpr.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(latihan.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else { // update
                try {
                    PreparedStatement prpr = setConnection().prepareStatement("update jurusan set nama_jurusan = ? where kode_jurusan = ?");
                    prpr.setString(1, name_jurusan.getText());
                    prpr.setString(2, kode_jurusan.getText());
                    var i = prpr.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(latihan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            cancelActionPerformed(evt);
            Read();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        name_jurusan.setText("");
        kode_jurusan.setText("");
        name_jurusan.setEnabled(false);
        kode_jurusan.setEnabled(false);
        baru.setEnabled(true);
        save.setEnabled(false);
        edit.setEnabled(false);
        delete.setEnabled(false);
        cancel.setEnabled(false);
        baru.requestFocus();
    }//GEN-LAST:event_cancelActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        if (tabel.getSelectedRow() == -1) {
            // Jika tidak ada baris dari jTable1 yang terpilih (terseleksi)
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih salah satu baris yang akan dihapus!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            // Jika ada baris dari jTable1 yang terpilih
            int pilihan = JOptionPane.showConfirmDialog(
                    this,
                    "Apakah yakin akan menghapus data?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION
            );
            if (pilihan == 0) { // tombol yes dipilih
                // menghapus baris dari jTable1 yang terpilih
                try {
                    PreparedStatement prpr = setConnection().prepareStatement("delete from jurusan where kode_jurusan = ?");
                    prpr.setString(1, kode_jurusan.getText());
                    var i = prpr.executeUpdate();
                    Read();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Data Jurusan Digunakan di Tabel lain");
                }
                cancelActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        kode_jurusan.setEnabled(false);
        name_jurusan.setEnabled(true);
        name_jurusan.requestFocus();
        baru.setEnabled(false);
        save.setEnabled(true);
        edit.setEnabled(false);
        delete.setEnabled(false);
        cancel.setEnabled(true);
        modeSimpan = false;
    }//GEN-LAST:event_editActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        if (tabel.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Silahkan pilih salah satu baris yang diinginkan!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            kode_jurusan.setText(
                    tabel.getValueAt( // mengambil nilai pada baris dan kolom dari
                            // jTable yang terpilih
                            tabel.getSelectedRow(), 0
                    ).toString() // konversi Object ke String
            );
            name_jurusan.setText(tabel.getValueAt(
                    tabel.getSelectedRow(), 1).toString()
            );
            name_jurusan.setEnabled(false);
            kode_jurusan.setEnabled(false);
            baru.setEnabled(false);
            save.setEnabled(false);
            edit.setEnabled(true);
            delete.setEnabled(true);
            cancel.setEnabled(true);
            baru.requestFocus();
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        setModal(true);
        Read();
        name_jurusan.setEnabled(false);
        kode_jurusan.setEnabled(false);
        save.setEnabled(false);
        edit.setEnabled(false);
        delete.setEnabled(false);
        cancel.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void kode_jurusanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_jurusanKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dupe = Search(kode_jurusan.getText());
            if (dupe == true) {
                dupe = false;
                int pilihan;
                pilihan = JOptionPane.showConfirmDialog(
                        this,
                        "data kosong atau kode jurusan " + kode_jurusan.getText() + " sudah ada!"
                        + "Apakah anda ingin mengubah/menghapus data?",
                        "Konfirmasi",
                        JOptionPane.YES_NO_OPTION);
//                System.out.println(pilihan);
                if (pilihan == 0) {
                    try {
                        Statement stm = setConnection().createStatement();
                        ResultSet rs = stm.executeQuery("select nama_jurusan from jurusan where kode_jurusan =" + kode_jurusan.getText());
                        ResultSetMetaData rsmt = rs.getMetaData();
                        while (rs.next()) {
                            name_jurusan.setText(rs.getString(rsmt.getColumnName(1)));
                        }
                        name_jurusan.setEnabled(false);
                        kode_jurusan.setEnabled(false);
                        baru.setEnabled(false);
                        save.setEnabled(false);
                        edit.setEnabled(true);
                        delete.setEnabled(true);
                        cancel.setEnabled(true);
                        modeSimpan = false;
                    } catch (SQLException e) {
                        System.err.println("Query error");
                    }
                } else {
                    kode_jurusan.setText("");
                    kode_jurusan.requestFocus();
                }
            } else {
                name_jurusan.setEnabled(true);
                name_jurusan.requestFocus();
                save.setEnabled(true);
            }
        }
    }//GEN-LAST:event_kode_jurusanKeyReleased

    private void kode_jurusanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_jurusanKeyTyped
        if (kode_jurusan.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_kode_jurusanKeyTyped

    private void name_jurusanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_jurusanKeyTyped
        if (name_jurusan.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_name_jurusanKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KelolaDataJurusan.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KelolaDataJurusan.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KelolaDataJurusan.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KelolaDataJurusan.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                KelolaDataJurusan dialog = new KelolaDataJurusan(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baru;
    private javax.swing.JButton cancel;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kode_jurusan;
    private javax.swing.JTextField name_jurusan;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
